### ISSUE TITLE
AppGyver - Android - Crash when displaying interstitial ad

### ISSUE THREAD

**Issue by stocknell2000** [floatinghotpot/cordova-admob-pro#102]
I'm using AppGyver, and the app is crashing with the following log:

java.lang.RuntimeException: Unable to start activity ComponentInfo{...../com.google.android.gms.ads.AdActivity}: android.util.AndroidRuntimeException: requestFeature() must be called before adding content

It works perfectly on iOS, not sure if I'm missing something?!

**Comment by mgmedia** [comment]
We're having the same issue - any progress here?

**Comment by mgmedia** [comment]
Has anyone else replicated or solved this?

**Comment by LH23** [comment]
any news about this issue? I'm having the same issue but I'm not using AppGiver.

**Comment by floatinghotpot** [comment]
need more logs to identify the problem ...

**Comment by mgmedia** [comment]
This is the response from Appgyver tech support, sounds like they won't solve this problem anytime soon.
----------------------------------------------------------------------------------------------------------------------------
Sounds like it might be conflicting with the Supersonic MPA structure – we've never used AdMob interstitial ads ourselves. The current push is towards 100% Cordova plugin compatibility and mitigating problems caused by MPA, but I can't promise any timeline.

**Comment by floatinghotpot** [comment]
This plugin is designed for cordova, and compatible tools like Intel XDK, Adobe PhoneGap build, Google CCA, etc. If AppGyver is not compatible with cordova yet, it may not work. It's strongly recommended to use Cordova compatible tools.
