### ISSUE TITLE
Non-test ads not showing

### ISSUE THREAD

**Issue by SteveEmmerich** [floatinghotpot/cordova-admob-pro#176]
I have an Ionic app using this package. I used the ionic demo for integrating it into my app. Everything works find in testing, but once I change isTesting to false none of my ads are showing. Any ideas?

**Comment by floatinghotpot** [comment]
Please make sure you are using valid ad unit Id and type.

You need create ad unit Id for the exact platform in admob portal, if using the id created for iOS in android app won't work.

**Comment by SteveEmmerich** [comment]
Yep I have admob set up with a banner and Interstitial, I put the correct
add unit ids in the admob.js from your Ionic example. I have is testing set
to false in the create banner from that same example. Everything looked
perfect until I changed that to false. Was there some setting in the admob
website I may have missed to change them from testing to live?

Also, thanks for the response I appreciate it.

On Mon, Jun 29, 2015 at 2:29 PM, Raymond Xie <notifications@github.com>
wrote:

> Please make sure you are using valid ad unit Id and type.
>
> You need create ad unit Id for the exact platform in admob portal, if
> using the id created for iOS in android app won't work.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/floatinghotpot/cordova-admob-pro/issues/176#issuecomment-116833844>
> .
>



-- 
Thank you for your time,
-Steve Emmerich

**Comment by floatinghotpot** [comment]
Please make sure you created ad unit for the correct platform.

And, if you are new AdMob account owner, it may take 24 hours to take effect.

**Comment by thirumurthy** [comment]
I created admob account 1 week before. Still i am not getting real ads if i set _isTesting: false_ . If this value is true, then banner displays test ads. Please anyone help on this

**Comment by agrapps** [comment]
Hi, i have the same issue, did you see whats the problem?

**Comment by vbellotto** [comment]
I have the same issue, my Ad unit ID: 'ca-app-pub-4159856889163914/1548689231'
the logcat when I change isTesting to FALSE:
09-15 00:43:26.467: W/Ads(17975): Invoke Firebase method getInstance error.
09-15 00:43:26.467: W/Ads(17975): java.lang.ClassNotFoundException: Didn't find class "com.google.android.gms.measurement.AppMeasurement" on path: DexPathList[[zip file "/data/app/io.ionic.starter-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]
09-15 00:43:26.467: W/Ads(17975): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
09-15 00:43:26.467: W/Ads(17975): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
09-15 00:43:26.467: W/Ads(17975): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
09-15 00:43:26.467: W/Ads(17975): 	at com.google.android.gms.ads.internal.scionintegration.b.a(:com.google.android.gms.DynamiteModulesA@11509236:167)
09-15 00:43:26.467: W/Ads(17975): 	at com.google.android.gms.ads.internal.scionintegration.b.a(:com.google.android.gms.DynamiteModulesA@11509236:152)
09-15 00:43:26.467: W/Ads(17975): 	at com.google.android.gms.ads.internal.scionintegration.b.g(:com.google.android.gms.DynamiteModulesA@11509236:43)
09-15 00:43:26.467: W/Ads(17975): 	at com.google.android.gms.ads.internal.request.c.a(:com.google.android.gms.DynamiteModulesA@11509236:47)
09-15 00:43:26.467: W/Ads(17975): 	at com.google.android.gms.ads.internal.util.b.run(:com.google.android.gms.DynamiteModulesA@11509236:4)
09-15 00:43:26.467: W/Ads(17975): 	at com.google.android.gms.ads.internal.util.af.call(:com.google.android.gms.DynamiteModulesA@11509236:3)
09-15 00:43:26.467: W/Ads(17975): 	at com.google.android.gms.ads.internal.util.ag.run(:com.google.android.gms.DynamiteModulesA@11509236:3)
09-15 00:43:26.467: W/Ads(17975): 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
09-15 00:43:26.467: W/Ads(17975): 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
09-15 00:43:26.467: W/Ads(17975): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
09-15 00:43:26.467: W/Ads(17975): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
09-15 00:43:26.467: W/Ads(17975): 	at java.lang.Thread.run(Thread.java:818)
09-15 00:43:26.467: W/Ads(17975): 	Suppressed: java.lang.ClassNotFoundException: com.google.android.gms.measurement.AppMeasurement
09-15 00:43:26.467: W/Ads(17975): 		at java.lang.Class.classForName(Native Method)
09-15 00:43:26.467: W/Ads(17975): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
09-15 00:43:26.467: W/Ads(17975): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
09-15 00:43:26.467: W/Ads(17975): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
09-15 00:43:26.467: W/Ads(17975): 		... 13 more
09-15 00:43:26.467: W/Ads(17975): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available
09-15 00:43:26.468: W/Ads(17975): The Google Mobile Ads SDK will not integrate with Firebase. Admob/Firbase integration requires the latest Firebase SDK jar, but Firebase SDK is either missing or out of date

**Comment by floatinghotpot** [comment]
@vbellotto , I found following errors in your usage:
1. if you use firebase together, use another plugin with id `cordova-plugin-admobpro-firebase`.
2. when pass the ad unit id to plugin, please use key `adId:`, not `id:`.

Here are the example code:
https://github.com/floatinghotpot/cordova-admob-pro/wiki/1.0-Quick-Start-Example-Code

**Comment by vbellotto** [comment]
@floatinghotpot thanks, for reply but I'm no using firebase in this project I was just trying to use admob free native first. 
I follow the steps in ionic documentation https://ionicframework.com/docs/native/admob-free/ and after creating a admob acount I tried to see how works the admob network performance and this error occurs.
I just install the follow plugin 

> $ ionic cordova plugin add cordova-plugin-admob-free
$ npm install --save @ionic-native/admob-free

**Comment by floatinghotpot** [comment]
Oh, I see. You are using the wrong plugin. It's a fork from my open source code, but that fork is maintained by someone else, so I cannot provide accurate answers to your questions.

To use my well maintained and supported plugin, see:
https://ionicframework.com/docs/native/admob-pro/

Though it's named as admob-pro, you can still use this plugin for FREE, until you earn enough to get a license.

You can use the plugin like this:
```bash
$ ionic cordova plugin add cordova-plugin-admobpro
$ npm install --save @ionic-native/admob-pro
```

You can find very detailed documents, demos, and video tutorials in the wiki page.
https://github.com/floatinghotpot/cordova-admob-pro/wiki

**Comment by ramilmammadov** [comment]
We have an ionic 2  app and we have tried both of admob free and admob pro . Rarely it showed ads , now i have installed admob pro , so there is no any blank or interstitial ads . What is the solition ?

**Comment by floatinghotpot** [comment]
@ramilmammadov I did not understand your problem yet. 

Here are some examples for your reference:
https://github.com/jaivehall/admob-ionic2-demo

Video tutorial on YouTube:
How To Add Banner Ads To Ionic 2 with AdMob Cordova Plugin, by pointDeveloper
https://youtu.be/dfHPlVvIUR0

After correctly integrating the plugin into your project, if still not working, could you please paste some error log or code here? We need some clue to find out what happens.
