### ISSUE TITLE
Show interstitial every X time

### ISSUE THREAD

**Issue by loris841** [floatinghotpot/cordova-admob-pro#190]
Hello, I have a problem showing interstital every X time.

I used setTimeout(AdMob.showInterstitial, 10000); but the interstitial never show.
If I use only the function showInterstitial() it show correctly.

Can anyone help me?

Thank you.

**Comment by floatinghotpot** [comment]
Your problem is a javascript syntax issue. 

setTimeout( function, ms );  // Here, it need a function instead of a object method.

Try this:
```javascript
window.setTimeout( function() {
   window.AdMob.showInterstitial();
}, 10000);
```

Remember, each time before call showInterstitial(), you need call prepareInterstitial() to preload the ad.

BTW, advice: do NOT show interstitial ad based on time interval for its poor user experience. Instead, at time of some UI switching stage.

**Comment by loris841** [comment]
Thank you floatinghotpot. I tried what you suggested but there is still the problem.

I think the settimeout doesn't work in phonegap but I don't know why...

Thank you.

**Comment by floatinghotpot** [comment]
I don't think so. You can test Google setTimeout () and test it with simple alert().

And see my above advice, poor user experience may result your apps removed from Google play store by Google team.
