### ISSUE TITLE
Ads not loading on Windows Phone 8

### ISSUE THREAD

**Issue by bradrlaw** [floatinghotpot/cordova-admob-pro#225]
I was updating an app for Windows phone 8 target and ads stop loading about a day ago on devices after receiving the latest 8.1 update.  I thought I might have messed up something in my app, but I just went ahead and downloaded and installed the demo app following the instructions in the docs.  The demo app is not loading / showing any ads as well.

I have tested it on a Lumina 635 (8.10.12397.895) and a 1520 (8.10.14219.341).  Both have the latest version of 8.1 installed and have internet access.  I have also tested the demo in the Windows phone emulator with the same results.  Is this an admob network issue?

**Comment by dmotion** [comment]
Same here - all my existing apps using this plug-in do not show any ads on the WP8 platform.

The exact same app on Android are showing, so it must be an issue with the server-side platform @Googles...

It happened before (six months ago) and it solved itself automatically, but this time it takes longer maybe (or they just pulled out the support for WP - like they always used to do).

**Comment by bradrlaw** [comment]
Is there any way to tell that no ad has been loaded? We could then change the css dynamically to at least get rid of the empty space...

**Comment by dmotion** [comment]
https://github.com/floatinghotpot/cordova-admob-pro/wiki/1.1-API-Overview

You can check if the banners fails to load, but I've not tested this; so I can't say if the event is triggered in our situation...

Also, I'm not sure we can "use" the empty space with CSS when an error occurred; it's not an element in the HTML-page (I think) but a native element in the app (coded in C#).

So you must check if an error has occurred first and than "resize" the browser-element (which contains the apps-content) to full-size, using a callback with C# (I guess... I'm not sure, because I'm not the author is this plug-in).

On Android it's more easy; the browser-element uses the overlap of the ad and ignores it when no ad is shown.

**Comment by riccardotreagles** [comment]
Same issue. 
Impressions from Admob network on windows phone stopped starting 17 sept. Any helps?

**Comment by dmotion** [comment]
Just checked another Admob plug-in for Cordova and that one isn't working as well.

So it seems a server-side / back-end issue at Google, and not really a plug-in related issue (or it's related to all Admob Cordova plug-ins... can't tell).

I will wait another few days, before I remove the plug-in at all; the black empty hole at the bottom of my app-screen isn't looking that nice..

**Comment by bradrlaw** [comment]
Is there a plugin for native windows ads?

Brad Lawrence

President & CEO, Trunica Inc.

brad@trunica.net



From:  "dMOTION.com" <notifications@github.com>
Reply-To:  floatinghotpot/cordova-admob-pro
<reply+009eeeb71094f71da8559d723bcc4c67feffad5a79f2448f92cf00000001121782449
2a169ce06630a4d@reply.github.com>
Date:  Monday, September 21, 2015 at 4:31 AM
To:  floatinghotpot/cordova-admob-pro <cordova-admob-pro@noreply.github.com>
Cc:  nielsen <brad@trunica.net>
Subject:  Re: [cordova-admob-pro] Ads not loading on Windows Phone 8 (#225)


Just checked another Admob plug-in for Cordova and that one isn't working as
well.

So it seems a server-side / back-end issue at Google, and not really a
plug-in related issue (or it's related to all Admob Cordova plug-ins...
can't tell).

I will wait another few days, before I remove the plug-in at all; the black
empty hole at the bottom of my app-screen isn't looking that nice..


Reply to this email directly or view it on GitHub
<https://github.com/floatinghotpot/cordova-admob-pro/issues/225#issuecomment
-141907723> .

**Comment by dmotion** [comment]
Native Window ads must be coded in C# / Silverlight.

But you can try this plug-in for Windows Cordova apps (not Windows Phone, but Windows (tablet/desktop) - 'though it does support WP as well (which isn't working right now - because of the ad-issue).

https://github.com/cranberrygame/cordova-plugin-ad-admob

**Comment by riccardotreagles** [comment]
Ok I will wait for the updates in the next days too.

**Comment by dmotion** [comment]
Yeah - but keep in mind that nothing has to be updated; it's not the plug-in that fails, but the service.

Even without updates on our side, the ads must be able to show up (it happened before, but this time it really takes longer).

**Comment by riccardotreagles** [comment]
ok :)

**Comment by dmotion** [comment]
Almost a week without ads on my Cordova Windows Phone apps - so I decided to dig in the code myself.

It looks like there is nothing wrong with the plug-in itself, because it does reserve space for the ad - and doesn't trigger any (failure) events.

After fiddling around with older version of the plug-in (I tested all branches and versions from 2.7.7 to 2.9.1) I found the solution - at least for my self...

The included .dll file (included in the plug-in) is not supported by Google (or is causing troubles anyway).

So I decided to replace these files;

* **\plugins\com.google.cordova.admob\src\wp8\GoogleAds.dll**
* **\plugins\com.google.cordova.admob\src\wp8\GoogleAds.XML**

Both files are included in the plug-in and at least the .DLL file is outdated - or something.

After deleting the files (you can also rename them - you to be save), I downloaded the original .DLL file / .XML file from Google itself;

* **https://developers.google.com/admob/wp/download**

Simply extract both files from the .ZIP to this directory;

* **\plugins\com.google.cordova.admob\src\wp8\**

Rebuild the solution and... the ads are showing up again - tested on both WP and Android (although I didn't change anything for the Android version).

For my own app (which was using plug-in version 2.7.1) I had to upgrade to the "local" plug-in version 2.7.8 before the ads showed up again;

* **https://github.com/floatinghotpot/cordova-admob-pro/archive/regio.zip**

But I'm not sure this is the case for everyone (I can not use higher version than 2.7.8 because my CLI of Visual Studio (which I use to build the apps) does not support the higher version of the plug-in (due to using the RPM).

**Hope this helps - please be careful when deleting files and updating; always have a good back-up and try all things first with a copy of your project.**

**Comment by riccardotreagles** [comment]
Thank you for your solution @dmotion.
Replacing the dll with the newest, seems to work fine also for me!

**Comment by dmotion** [comment]
Glad it worked for you as well!

The .DLL-file (the "communicator" between the plug-in and Google Ad-services) in the original plug-in seems outdated (created way back in 2013).

So updating this .DLL-file with the newest one (see the link in my comments above) can solve the problems...

*I hope the dev will integrate / update the new .DLL-file in his plug-in... and remember **never** download .DLL-files from third-party sites - only from the original sites (just to be sure).*

**Comment by bradrlaw** [comment]
Worked for me as well, thanks for getting us back on track!

**Comment by floatinghotpot** [comment]
Thanks to dmotion for pointing out the root cause, the DLL was outdated.

I've updated the DLL in the plugin and re-published to npm (plugin id: cordova-plugin-admobpro), but as cordova plugin registry is deprecated and now read-only, the plugin with id "com.google.cordova.admob" cannot be updated. 

If your cordova CLI in visual studio is newer than 5.0, you can directly add plugin ```cordova-plugin-admobpro```.

Or else, you can try use npm to download it to your local folder, ```npm install cordova-plugin-admobpro``` then you can find the plugin in ```./node_modules/cordova-plugin-admobpro```, then add it from local.
