### ISSUE TITLE
input fields are overlapped by the keyboard

### ISSUE THREAD

**Issue by RonnySchleicher** [floatinghotpot/cordova-admob-pro#226]
#### A current PhoneGap App on Android with a input field:

![image](https://cloud.githubusercontent.com/assets/1914203/10018148/a6c6c550-6134-11e5-8a8c-26da9dbf7550.png)

#### Click into the input field:

![image](https://cloud.githubusercontent.com/assets/1914203/10018154/b7f044f0-6134-11e5-966c-46bce0dd3a96.png)

Everything okay. The input field can be used.

#### Add Addmob like the documentation into the index.html

![image](https://cloud.githubusercontent.com/assets/1914203/10018199/1d416190-6135-11e5-8b8b-cbea77dd9aba.png)

At first glance, everything is okay

#### But if you click in the input field, it is overlapped by Keyboard

![image](https://cloud.githubusercontent.com/assets/1914203/10018213/329d7a56-6135-11e5-92f7-49f0cf5fe52d.png)

**Comment by RonnySchleicher** [comment]
#### Used Version and Device
"cordova-plugin-whitelist": "1.0.0",
"cordova-plugin-device-motion": "1.1.1",
"cordova-plugin-media-capture": "1.0.1",
"cordova-plugin-device-orientation": "1.0.1",
"cordova-plugin-network-information": "1.0.1",
"cordova-plugin-contacts": "1.1.0",
"cordova-plugin-device": "1.0.1",
"cordova-plugin-battery-status": "1.1.0",
"cordova-plugin-file-transfer": "1.2.1",
"cordova-plugin-geolocation": "1.0.1",
"cordova-plugin-globalization": "1.0.1",
"cordova-plugin-inappbrowser": "1.0.1",
"cordova-plugin-media": "1.0.1",
"cordova-plugin-dialogs": "1.1.1",
"cordova-plugin-vibration": "1.2.0",
"cordova-plugin-splashscreen": "2.1.0",
"cordova-plugin-console": "1.0.1",
"cordova-plugin-statusbar": "1.0.1",
"cordova-plugin-admobpro": "2.9.2",
"cordova-plugin-file": "3.0.0",
"cordova-plugin-extension": "1.1.4"

**Comment by RonnySchleicher** [comment]
#### My changes on the original source code

**Comment by floatinghotpot** [comment]
Please see same issue #23, and try the workaround suggested by @Rickgbw.

**Comment by RonnySchleicher** [comment]
#### Unfortunately, the workaround does not work with my problem.
My problem is NOT the banner position. My problem is the covered input area at the bottom. And that happens only when the AddMob banner is displayed.

**Comment by RonnySchleicher** [comment]
My main problem is that the plugin on iOS behaves unlike Android. The problem described above does not occur in iOS. Even with Banner activated it behaves like on picture 1 and 2.
Of course, I can now install a workaround in my Android app, and the banner area with 'Overlap: true' manage itself. But that is actually not in the sense of a hybrid app and phylosopie from PhonaGap and PhonaGap plugins.

**Comment by imskull** [comment]
Same problem, the web view doesn't shrink when keyboard appears, seems my `android:windowSoftInputMode="adjustResize"` is changed by the admob plugin.

**Comment by hotgeart** [comment]
@RonnySchleicher did you find a way ? Same probleme [here](https://github.com/floatinghotpot/cordova-admob-pro/issues/250)

**Comment by floatinghotpot** [comment]
After carefully study, the root cause is identified: 
* When focus in input area, the soft keyboard will resize the webview. 
* When the ad banner displayed in split mode (overlap:false), it will also resize the webview to avoid overlap the web content. 
* If both resize the webview at the same time, this will cause conflict.

When soft keyboard display, it will always try to resize the existing view at bottom. If the banner ad displayed at bottom, it will give up resizing. As the soft keyboard code is from Android system, this issue cannot be resolved perfectly.

This issue happens when banner at bottom, and UI has input box or textarea.

To resolve this issue, the soft keyboard have to find the webview as the content view at bottom and resize it correctly.

Here a few workaround methods are suggested to avoid the issue happen:
* solution 1: When you have some input box or textarea on UI, avoid show banner at bottom. You can show banner at top.
* solution 2: Hide bottom banner when input/textrea get focus, and show it again when input/textarea blur.
* solution 3: Use overlap:true (as the banner will overlap web content, you need reserve some margin area for it.)

It's now documented in [Known Issues & Solution Workaround](https://github.com/floatinghotpot/cordova-admob-pro/wiki/Known-Issues-&-Solution---Workaround#if-banner-at-bottom-soft-keyboard-overlap-input-box-if-its-in-bottom-half-area)

**Comment by floatinghotpot** [comment]
Good news, it's fixed. 
When banner at either bottom or top, it works perfectly with soft keyboard. 
Please update to cordova-plugin-admobpro v2.11.0, enjoy. :-)

**Comment by floatinghotpot** [comment]
![img_3293](https://cloud.githubusercontent.com/assets/2339512/12327047/3827ffb2-bb0f-11e5-880f-65337212985c.jpg)
