### ISSUE TITLE
certain admob interstitial hangs ionic/cordova?

### ISSUE THREAD

**Issue by jtbdevelopment** [floatinghotpot/cordova-admob-pro#233]
Has anyone seen something like this?  

I've only observed on android / crosswalk build so far (not seen the specific kind of ad on ios yet).  Ionic 1.1, htc m8 phone

Have a banner ad and an interstitial.  Banner is fine, rotating away.  Interstitials work fine until I get an interactive one for I think game of war (looks like a cartoon version of kate upton) where you can move a castle onto the board or some such.  When I exit that ad, whole app is frozen.  No input does anything.  Banner ad stops rotating.  Only thing to do is kill the app.  It's specifically that ad as far as I can tell, but I've just started and not seen many kinds of ads yet personally.

I have not spotted anything meaningful in adb or javascript console

**Comment by cobbdb** [comment]
Yeah I just got a few crash reports of basically this same thing happening. Just started looking into the issue - not totally convinced it's the plugin's fault though. Some of the ad content that comes down from AdMob's pipe is really shocking how poorly coded it is.

Reported on Moto G with KitKat

**Comment by jtbdevelopment** [comment]
Thanks, I wasn't particularly blaming the plugin or the crosswalk browser or cordova, I was just looking to see if I was the only one (which would have made it my problem obviously :) )

**Comment by cobbdb** [comment]
Just a quick update, after doing some digging.. I'm almost positive this is just one the problems caused by AdMob's requirement to run on the UI thread. This also explains why framerate tanks on every ad refresh. From what I've seen so far I think this is Google's problem and there doesn't seem to be much that can be done about it. There have been some people out there who tried moving the IO off of the UI thread, but all the posts I found were saying it caused crashes sadly.

**Comment by jtbdevelopment** [comment]
I'm closing as I suspect you're right and I haven't seen the issue since.
