### ISSUE TITLE
Private code? cordova-generic-ad.jar

### ISSUE THREAD

**Issue by imskull** [floatinghotpot/cordova-admob-pro#242]
Hello,

I found this plugin depended dev's another project [cordova-plugin-extension](https://github.com/floatinghotpot/cordova-extension), `cordova-plugin-extension` depends a private java library 'cordova-generic-ad.jar' . so does it mean this "pro" plugin is not fully open source? should I buy license to access the `cordova-generic-ad.jar` source code?

Thanks.

**Comment by floatinghotpot** [comment]
The cordova-extension plugin is the common architecture to keep all the ad plugins providing the same API, so that user can easily switch from one ad service to another. It's key logic part of the ad plugins, but not fully open source and not for sale. As I do not hope to see many derived plugins with exactly same feature,  which may confuse users, as they only copy my code and claim as their own, like this one: https://github.com/appfeel/admob-google-cordova

**Comment by imskull** [comment]
Thanks for quick reply! 
but I'm afraid the private code may scare people like me, especially for such a revenue-relative plugin. hope you will eventually find a solution to be able to disclose all private code, meanwhile protect your credit for this good plugin.
