### ISSUE TITLE
When banner showed at bottom, soft keyboard hide the content.

### ISSUE THREAD

**Issue by hotgeart** [floatinghotpot/cordova-admob-pro#250]
I've an issue with this plugin. When the plugin is active the keyboard hide the content.

![f](http://i.imgur.com/MBnmfeh.png)

When I click on the input (I can't scroll more than this): 

![x](http://i.imgur.com/nKJtkgj.png)

Without ads no problem:
![w](http://i.imgur.com/m8vUK0m.png)

**Comment by hotgeart** [comment]
I'm not the only one : http://forum.ionicframework.com/t/issue-in-admob-plugin-pro/30084

found many posts/topics with the same problem.

**Comment by MazzMazz** [comment]
Yup have the same problem.

Also if i click in an input field, before the ad loaded, the place where the keyboard should be is black and doesn't hide anymore.

**Comment by laziaf** [comment]
I have same problem here, when keyboard open before admob, keyboard just goes blank, and when admob show before keyboard i can't scroll until end of the page (keyboard hiding admob and my last element in the page)

**Comment by neslinesli93** [comment]
+1

**Comment by floatinghotpot** [comment]
After carefully study, the root cause is identified: 
* When focus in input area, the soft keyboard will resize the webview. 
* When the ad banner displayed in split mode (overlap:false), it will also resize the webview to avoid overlap the web content. 
* If both resize the webview at the same time, this will cause conflict.

When soft keyboard display, it will always try to resize the existing view at bottom. If the banner ad displayed at bottom, it will give up resizing. As the soft keyboard code is from Android system, this issue cannot be resolved perfectly.

Here a few workaround methods are suggested to avoid the issue happen:
1. When you have some input box or textarea on UI, avoid show banner at bottom. You can either hide banner, or show banner at top.
2. Use overlap:true (as the banner will overlap web content, you need reserve some margin area for it.)

**Comment by floatinghotpot** [comment]
Good news, it's fixed. 
When banner at either bottom or top, it works perfectly with soft keyboard. 
Please update to cordova-plugin-admobpro v2.11.0, enjoy. :-)

**Comment by floatinghotpot** [comment]
![img_3293](https://cloud.githubusercontent.com/assets/2339512/12327047/3827ffb2-bb0f-11e5-880f-65337212985c.jpg)

**Comment by neslinesli93** [comment]
Thanks for the update!
However, I get the same problem (ad is not shown after tapping on input field), and I'm using overlap=true

**Comment by maxlinux2000** [comment]
Hi,

any way to hide the banner when the user open the soft keyboard?
