### ISSUE TITLE
IOS control center issue

### ISSUE THREAD

**Issue by Tinhui** [floatinghotpot/cordova-admob-pro#266]
I am using ionic to build a media player app. Once I added an Interstital banner, it will show up a YouTube link in IOS control center. Even I added remote control plugin , it alsway auto override my setting.
Is this issue related to admob plugin ? Please help, thanks.

![img-20151209-wa0024_1](https://cloud.githubusercontent.com/assets/15526801/11678517/b1742222-9e83-11e5-95bf-3ccd424ea667.jpg)

**Comment by floatinghotpot** [comment]
I don't think it's caused by admob plugin, at least I never receive such report. 

It's simple to verify this. just go to your admob portal, change your ad settings, only accept text and picture ad, exclude video. then try again, can you still see the youtube link?

Since your app is a media player app, is there any other reasons?
