### ISSUE TITLE
Work with Intel XDK

### ISSUE THREAD

**Issue by floatinghotpot** [floatinghotpot/cordova-admob-pro#304]
![1](https://cloud.githubusercontent.com/assets/2339512/12910184/251db34c-cf43-11e5-81f8-bf0528b0c8b9.png)

![2](https://cloud.githubusercontent.com/assets/2339512/12910198/4d01b408-cf43-11e5-9d48-563292bfd2a1.png)

![3](https://cloud.githubusercontent.com/assets/2339512/12910201/5e205938-cf43-11e5-8724-db7c3ba0deb5.png)

![4](https://cloud.githubusercontent.com/assets/2339512/12910215/82490544-cf43-11e5-91d3-08a09fc33c4f.png)

![5](https://cloud.githubusercontent.com/assets/2339512/12910221/8cbcf72e-cf43-11e5-8330-65b268a49a3b.png)

**Comment by floatinghotpot** [comment]
See demo project:
https://github.com/floatinghotpot/admob-demo-xdk

**Comment by arjankuijpers** [comment]
@floatinghotpot 
<img width="1281" alt="schermafbeelding 2016-02-11 om 17 21 35" src="https://cloud.githubusercontent.com/assets/1952012/12982193/10cd97a2-d0e4-11e5-9ac9-14296178b5c2.png">

this is what I get when building for iOS.

the demo fails as well: 
<img width="1286" alt="schermafbeelding 2016-02-11 om 17 45 25" src="https://cloud.githubusercontent.com/assets/1952012/12982940/6700784e-d0e7-11e5-92df-94b31784ea7b.png">

I'm on early access, I would really like to see a screenshot of your example project succeeding the iOS build, because I have tried several times over the past months and it still fails.

**Comment by arjankuijpers** [comment]
This is what i found in the build log: 

ld: 28 duplicate symbols for architecture arm64

**Comment by JuergenRoth** [comment]
same here.
