### ISSUE TITLE
Ads show up periodically

### ISSUE THREAD

**Issue by alex-wilmer** [floatinghotpot/cordova-admob-pro#321]
I'm not sure if this has anything to do with admob, but it seems like the ads show up 1/8 times that I restart my app.

Is there a clear reason for this? The success callback always fires OK

**Comment by technotip** [comment]
set this and test
AdMob.createBanner({
adId     : 'ca-app-pub-xxxxxxxxxxxxxxxx/xxxxxxxxxx',
 isTesting: true in 
});

i.e., set isTesting: true and try once. I guess the problem persists because adMob is not able to fill ads 100% of the times. It happens when you create a new ad unit and implement it immediately. It takes some time to start showing ads 100% of the time.

**Comment by floatinghotpot** [comment]
Yes, @technotip answer is correct.
