### ISSUE TITLE
Does it support DFP Interstitial?

### ISSUE THREAD

**Issue by loganthomison** [floatinghotpot/cordova-admob-pro#351]
Is it possible to use DFP to create an interstitial ad?

**Comment by floatinghotpot** [comment]
Yes. This plugin support both AdMob and DFP with same API.

Just create your DFP ad, and pass the DFP ad unit id to the API.

**Comment by bgondy** [comment]
Hi, I try to implement a DFP interstitial in my Ionic app but it is not working for now.

For testing purpose, I've created a new blank app and copy/pasted the `admob_simple.js` content. It works as is but when I remove the `AdMob.createBanner(options);` call (because I just want the  interstitial), the interstitial is not working anymore.

So I was wondering if it is possible to have a standalone DFP interstitial.

Thanks in advance.

**Comment by floatinghotpot** [comment]
Yes, banner / interstitial can be used separately.

Remember to use `isTesting:true` when run in emulator or device for test purpose. Running a real Ad in emulator won't work, if I remember correctly.

```javascript
    AdMob.prepareInterstitial({
        adId: admobid.interstitial,
        isTesting: true,
        autoShow: true
    });
```

**Comment by bgondy** [comment]
Thanks @floatinghotpot, The `isTesting` property was missing. Now, I can display the test ad with the AdMob code provided in `admob_sinple.js` but it is not working with my DFP code. I don't know if it is a configuration problem with DFP or if it is the plugin.

With the DFP code, in the list of web views I can inspect in Chrome (chrome://inspect/#devices), I can see two webviews for my app: one for the webapp itself and the other one for the interstitial which seems to be empty.

In my app, I call`prepareInterstitial()` (with the `isTesting` property set to `true`) while a custom splash screen is shown (Not only an image). When the splashscreen is ready then, I show the interstitial (with `showInterstitial()`). The event `onAdLoaded` is fired but the interstitial is not showing, neither the close button. The `onAdDismiss` event which I listen to redirect the user is not fired and the user is blocked.

Do you have ever experienced a similar issue with DFP ?

**Comment by floatinghotpot** [comment]
Pleas play with the simple demo use case, and confirm your DFP resource no problem first.

**Comment by bgondy** [comment]
As I said, I can't get it working either when I use the `admob_simple.js` file, I get the same behavior as in my app: interstitial not showing and I have an empty webview for the ad. I have no idea if it is a configuration issue with DFP or if it is with the plugin that's why i'm asking if you have ever had the same behavior since I can't confirm if the DFP configuration is OK or not.

I'm going to make some additional tests. If you have any idea, feel free to share :).
