### ISSUE TITLE
App freezes when calling AdMob.createBanner()

### ISSUE THREAD

**Issue by rahmadid** [floatinghotpot/cordova-admob-pro#370]
Hi,

When using cordova-plugin-admobpro v2.16.0 and cordova-plugin-extension v1.5.1, my android app often (very often) freezed when calling AdMob.createBanner().
I believe it had something to do with the new checking to 'adlic.rjfun.com' address.

When freezed, pressing the back button several times couldn't close the app. However, it turned out that the app didn't completely freeze, as after a very long time, the AdMob.createBanner() finally finished and execution resumed (the app closed immediately because I pressed the back button earlier).

Here is a few lines from the log that might be useful:

```
04-09 01:53:52.606 16789-17171/xxx.xxx D/GenericAdPlugin: createBanner: , true
04-09 01:53:52.606 16789-17171/xxx.xxx W/PluginManager: THREAD WARNING: exec() call to AdMob.createBanner blocked the main thread for 1006468ms. Plugin should use CordovaInterface.getThreadPool().
```

I also tested running the app without internet connection. The log said something like 'cannot reach adlic.rjfun.com' (sorry, I forgot the exact words) when calling AdMob.createBanner(), but the app ran successfully (didn't freeze).

At this moment, I have to go back to cordova-plugin-admobpro v2.12.0 and cordova-plugin-extension v1.2.9, the version without the checking to 'adlic.rjfun.com', to make the AdMob.createBanner() run successfully.

My work environment:
-cordova-plugin-admobpro installed from 'https://github.com/floatinghotpot/cordova-admob-pro'.
-Cordova CLI 6.1.1
-Cordova-Android 5.1.1
-Tested on android 6.0, 5.1.1 and 4.2.1, all real devices (not virtual).
-Reliable internet connection via wifi.

Please let me know if you need other info.

Thanks.

**Comment by floatinghotpot** [comment]
Thanks for the bug report. I will look into this issue.

**Comment by calanti** [comment]
Think I am experiencing the same issue but only on my Asus Zenfone 2 (Android 5.0) and any build later than 2.13.0. The latest build (2.17.0) seems to be working correctly on my Samsung S2 (Android 6.0.1) and Samsung S4 (Android 5.0.1)

On my Zenfone 2 I tried with 2.17.0, 2.16.1 and 2.15.0, AdMob.showBanner(AdMob.AD_POSITION.BOTTOM_CENTER) will display the ad correctly but my app disappears and just leaves a white screen. It seems quite intermittent though, it functions correctly the first time I install/open the app, one time it took a few seconds and resumed, the rest of the time I need to force close the app (but I never gave it more than 10 seconds to sort itself out.. so maybe it would have eventually)

FYI my setup has AdMob.createBanner with autoShow false during app initialisation. I don't do anything until the "onAdLoaded" event is fired, since it seems the success/fail callbacks of createBanner do not take into account internet connectivity. (I still get success callback when "onAdFailLoad" is triggered due to a network error) 

Cordova CLI 6.1.0
Cordova Android 5.1.1

Hope this helps

**Comment by calanti** [comment]
Damn, just had this issue twice with 2.13.0 (Zenfone 2). Seems to resolve though if I press home / recent screen then go back to the app, or if I turn off the screen and unlock again.

**Comment by floatinghotpot** [comment]
The createBanner() only check whether your adId is given, the result will fire a 'onAdLoaded' or 'onAdFailLoad' event.
