### ISSUE TITLE
AdMob Rewared Interstitial and Native Ads

### ISSUE THREAD

**Issue by technotip** [floatinghotpot/cordova-admob-pro#391]
Hi Guys,

Can we use Rewared Interstitial and Native ad units of AdMob using AdMob Pro plugin?

If yes, can you please point to the documentation of implementing it?

**Comment by neslinesli93** [comment]
I am pretty sure there is no support yet for native ads, however, it doesn't look like too much of a hassle:
[here is the documentation for android](https://firebase.google.com/docs/admob/android/native) and it would be fantastic to have it integrated in cordova-admob-pro

**Comment by Purus** [comment]
I got official email communication Google on the official launch of Native Ads..

**Comment by floatinghotpot** [comment]
After implemented native Ad for Facebook AudNet and Flurry, I've looked into Google AdMob for the native Ad feature a few weeks ago.

Unfortunately, it's very very hard to implement AdMob native Ad into Cordova plugin.

The reason is, the AdMob SDK require the native Ad resource being displayed in a few real native view and layout, which is not possible to insert into HTML5 DOM.

Unlikely, Facebook AudNet and Flurry allow getting Ad resources (picture / text) and display as you like (even insert into HTML5 DOM), and accept the user click with a native view (which can be done with some hacking method).

BTW, the rewarded video interstitial has been supported. See tracker #332

**Comment by matte5031** [comment]
Is there anyway to maybe make a request to Google AdMob about this or atleast notify them about it. Maybe they can do something about it, they seem hard to get in contact with but maybe someone knows how to contact them, thanks.

**Comment by Divyaadz** [comment]
Any workaround to implement admin native ad in phonegap without plugin?

**Comment by InternetMaster1** [comment]
Any update on running Admob Native ads inside the content of the app via this plugin? 

Btw, would the below link help in any way or this talks about only Admob Banners & Interstitials?
http://www.thedevline.com/2014/02/how-to-admob-native-android-sdk.html

**Comment by evyatar** [comment]
@floatinghotpot I think there is a way with - Native Ads Advanced:
https://firebase.google.com/docs/admob/android/native-advanced

**Comment by InternetMaster1** [comment]
Wow, fingers crossed....

**Comment by halkoy** [comment]
Please support Admob native ad for cordova

**Comment by InternetMaster1** [comment]
Yes pretty please....

**Comment by InternetMaster1** [comment]
Yes pretty please....

On 30 Dec 2016 22:10, "halkoy" <notifications@github.com> wrote:

Please support Admob native ad for cordova

—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub
<https://github.com/floatinghotpot/cordova-admob-pro/issues/391#issuecomment-269792609>,
or mute the thread

**Comment by charlizesmith** [comment]
Hi Any updates? Thanks a ton!

**Comment by floatinghotpot** [comment]
same as #461, close this one and follow up there.
