### ISSUE TITLE
adlic.rjfun.com Request on every App Start

### ISSUE THREAD

**Issue by Rebsos** [floatinghotpot/cordova-admob-pro#403]
Everytime a user opens my App, this plugin sends a request to http://adlic.rjfun.com with my app ID. Then the Server sends multiple parameters back (i don't know what the plugin can do with them). 

You mentioned that Google contacts you to do some server-side blacklist checks.

How does this help anyone? The users, app developers or Google? Please tell me for what this is and how it works. Why does not Google block the apps itself?

Also there are two IPs requested. If i block both my App freezes. So if your server goes down, all my customers couldn't use my App.

**Comment by floatinghotpot** [comment]
As everyone knows, this plugin is very simple to use and very easy to use it to generate revenue. A few percentage of the app developers abuse this plugin, make many low quality apps with just a few plain text pages, violate Google AdMob rules severely, and bring loss to Google and advertisers. 

If this cannot be prevented, Google may regards the ad traffic from Cordova app and all apps with this plugin are all very low quality. There is risk that Google may take action to simply block any cordova apps using this plugin, which will mean death of this project, and you guys cannot use it any more. 

That's why some basic pre-check has to be done before allowing the plugin work. If a new app is such a bad app, it will be blacklisted. When the plugin initialized, it will check whether the app id is in blacklist, if yes, the plugin will refuse to send Ad request to AdMob ad server.  

The adlic service is in Amazon cloud, very stable and continuously running over several months without any faults. With defensive design, even when the service is down with accidents, it won't impact your app and ad requests.

**Comment by floatinghotpot** [comment]
The 2 IP you tried blocking, one is adlic, another is admob. It will first check adlic for authorities, then send ad requests to admob. If you block both, the ad plugin won't work.
