### ISSUE TITLE
Not only 2% of Sharing ad traffic?

### ISSUE THREAD

**Issue by userweb** [floatinghotpot/cordova-admob-pro#450]
@floatinghotpot   say 2% :

"Sharing ad traffic means that, when using my plugin to present the ad to user, random 2 out if 100, will use my ad unit, 98 use yours, so that we can both benefit."
https://github.com/floatinghotpot/cordova-admob-pro/wiki/License-Agreement#2-win-win-partnership
 
BUT  its  not  true "2% " 

see the code
https://github.com/userweb/expose-liar-plugin/blob/master/GenericAdPlugin.java#L380

he make a request to "http://adlic.rjfun.com/adlic" and get a JSON  with the  "adlicRate"

 this.testTraffic = (new Random()).nextInt(100) < this.adlicRate;

in my tests  adlicRate  its   30%  of  "Sharing ad traffic"

@floatinghotpot   why did you  lie?

please  be honest with community !!

**Comment by floatinghotpot** [comment]
Did you use a fake license key? As I did find some guys attempt to crack this plugin and send fake license key.

In normal situation, if a valid license key is used, will 100% use your own id and no more ad sharing. If no license key used, then sharing 2%. BUT, if a fake license key is used, some punishment will be added for the crack behavior.

Please let me know your package id and license key for a double check.

**Comment by userweb** [comment]
@floatinghotpot      i don't use license key and your "sharing ad traffic"  its  30%  

please  see  the  code again  

in my app  "this.validatedLicense"  is empty string
https://github.com/userweb/expose-liar-plugin/blob/master/GenericAdPlugin.java#L370
and your  server  return  a JSON  with      r:30 
https://github.com/userweb/expose-liar-plugin/blob/master/GenericAdPlugin.java#L380
so ....  you lied about 2%    

please be honest with community !!

**Comment by floatinghotpot** [comment]
Here are some examples of fake license keys, we found from the crack/attack behaviors: 
```
-6849' IN BOOLEAN MODE) UNION ALL SELECT 1853,1853,1853,1853,1853,1853,1853,1853,1853,1853#

toto/20d022b75dee5fc4dd18cf13a97bf003
```

Why not tell us your package id and license key for a double check?

**Comment by userweb** [comment]
@floatinghotpot   

**I DON'T USE ANY LICENSE**

**Comment by userweb** [comment]
@floatinghotpot   why?????
please be honest with community !!

**Comment by floatinghotpot** [comment]
I just wanna do a double check if any mistakes, tell me your package id please.

**Comment by userweb** [comment]
@floatinghotpot  check  your  CODE  
https://github.com/userweb/expose-liar-plugin/blob/master/GenericAdPlugin.java#L380

**Comment by floatinghotpot** [comment]
We have some automatic logic in server side to protect from crack/hack behavior, I am not sure if it's triggered in your situation. Please tell me your package id, so that we can double check whether you said is true.

**Comment by floatinghotpot** [comment]
Hey, @userweb, we wanna dig into this issue, please help to provide more details, we need your package id for a troubleshooting.

**Comment by becvert** [comment]
Can we get an update on this please?

**Comment by floatinghotpot** [comment]
Not yet, userweb did not provide us the package id. If anyone face similar issue, please provide us more details so that we can do troubleshooting to identify the root cause.

**Comment by becvert** [comment]
OK. But did you double check your code just in case?

Also I think you need to be more upfront with the 2% ad sharing.
It should be one of the first thing we see in the README.
The Licence Agreement page is hidden in the Wiki's right hand side menu.

And how can we check the adclick rate? Could you provide some sort of logging at runtime?

Thank you

**Comment by userweb** [comment]
@floatinghotpot   you  stolen a lot of money from community.

WHY   dependency   "cordova-plugin-extension"   is not   "full"  open-source?

this file https://github.com/floatinghotpot/cordova-extension/blob/master/src/android/cordova-generic-ad.jar

stolen  more  than  2%  
 
please be honest with community !!

without your  plugin  my ads its  more 20-30%  of  dollars


@becvert   the code from this plugin  stolen  your money

PS:  my package id is:  

(new Random()).nextInt(100) < this.adlicRate;
.....

        if(this.testTraffic) {//if  stolen .....
            if(this.adlicBannerId.length() > 0) {
                adId = this.adlicBannerId; // your  fucking ads ID  from your  server adlic.rjfun.com/adlic
            } 
            .....

       }


please be honest with community !!

please be honest with community !!

please be honest with community !!

please be honest with community !!

**Comment by floatinghotpot** [comment]
@userweb is a newly created anonymous user, refuse to provide package id. So it's hard for us to identify the root cause. If anyone encounter the similar situation, please provide us some clues for troubleshooting, and we will correct it if anything really wrong.

I have 139 projects on github (original source, and forked/improved), mainly for my own use, then open to the community by the way. If you feel it useful, use it. If not, just ignore it and find something better.
https://github.com/floatinghotpot?tab=repositories

Like wekan, it's a fully open source project I contributed (it's created by Maxime Quandalle, and I improved it for our own needs, as we use it in our project management), very recommended.
https://github.com/wekan/wekan

If you trust this plugin, and hope to get some support, try donating $20 to get a commercial license. You will be supported with higher priority. There are many commercial customers, still now, none of them complains. 

If not, there are also plenty of totally free options. As you guys can see, here is the fully open source version of admob plugin. You guys can fork it, read and understand the full open source code, and add/delete any lines of code as you wish.
https://github.com/floatinghotpot/cordova-plugin-admob

There are some other alternatives, some guys simply copy my code (instead of fork, they just copy, change the ad sharing id to their own, then claim as their own plugin, and they even not mentioned it's derived from my code), like these: 
https://github.com/appfeel/admob-google-cordova
https://github.com/sunnycupertino/cordova-plugin-admob-simple

BTW, You guys may wonder, as I wrote so many code for free, if I don't get ad sharing or donation, what I make living from? Okay, welcome to try my new game (it's rated 4.4 on Google Play, I am confident it earns more than some of you): 

Google Play:
https://play.google.com/store/apps/details?id=com.unicgames.tankcraft

Apple AppStore:
https://itunes.apple.com/app/tankcraft.io/id1128668192?mt=8

Enjoy coding and monetization, see you in AppStore.

**Comment by becvert** [comment]
Hi @floatinghotpot

Why censoring @userweb 's last message?

Personnaly I didn't say you were cheating or that @userweb was right.
But he's raising a good point.

You're making a living out of the 2% ad sharing, that's fine with me.
You even deserve it as you're helping out the community.

But that's our money we're talking about too, and as an small indie every buck count.
We need trust, transparency and reinsurance,
I'd love you to tell me you double check, we all make mistake.

Anyway, I still plead for my previous points:
1 - be more up front with the ad sharing (I have doubts that every one knows about it)
2 - provide a way to check the adlicRate

Thank you

**Comment by floatinghotpot** [comment]
@becvert I just delete some rude shouting, as you can see, I did not delete any content supporting his points and against me.

I just ask for a package id so that I can try troubleshooting and double check, but @userweb always avoid positive response, just keep shouting rudely. It's not a correct way for positive communication. What else can I say?

As I mentioned in last post, there are plenty of free and fully option source options. For those who don't trust the plugin, please stop using my code, it's a simple way make you feel safer and make me feel happy.

Time is money, please don't get me tangled. I won't respond again. Thanks.

**Comment by becvert** [comment]
no worries.
but again please just be more up front with the 2% ad sharing.
advertise it more clearly for fairness.

**Comment by userweb** [comment]
@floatinghotpot    WHY  delete my  comments?????
Are you  afraid?

PLEASE   EXPLAIN  this  FOR COMMUNITY:

1 - Please  explain  Why  dependency  "cordova-plugin-extension"  is not full open source????
https://github.com/floatinghotpot/cordova-admob-pro/blob/master/plugin.xml#L24


2 - What this package do??? 
"import com.rjfun.cordova.ad.GenericAdPlugin;"


3 - What  this .jar   do??
https://github.com/floatinghotpot/cordova-extension/blob/master/src/android/cordova-generic-ad.jar


4 - Why your plugin   makes a request  to "http://adlic.rjfun.com/adlic"  every time ???????

5 - Why without your plugin  I got  more 20%-30%  of  dollars/views/clicks  from admob ???




PLEASE   EXPLAIN   FOR COMMUNITY  !!!!!!!!!!

**Comment by kabus202** [comment]
I did not know about the 2%, wtf?

**Comment by jmelvin** [comment]
To use this FREE high-quality plugin, I have no problem with the 2% royalty, as documented in the README.  If the closed code were reverse engineered and it was proven to be more than 2% for legitimate uses of the plugin, that would be a problem.  For illegitimate uses however, perhaps the plugin should not work at all.

Separately, I completely understand why some parts of the code might be closed source.  If the code were completely open, it would be even more vulnerable to copy/paste/rename.  Such ripoffs have already been reported.  Outright stealing of hard work stifles innovation and sharing.

**Comment by rene-molineux** [comment]
Salut! 

I came to this plugin when reviewing adsense alternatives for a customer cordova project. I find this issue quite interesting, so I took some time to analyse further. Here are my **personal** opinions.

There are a number of quite puzzling things with this plugin, some of which are quite frankly just wrong! I've checked the code _userweb_ has posted and here are a couple of observations that the authors of the plugin should address.

## Privacy Issues

There is quite a serious privacy breach with this plugin. Every time your app users start your app, their devices will make a POST HTTP request to `http://adlic.rjfun.com/adlic` where they'll send your app package id, device os, but most importantly the **IP address** of the user's device! It is unclear why this is being done from the plugin's documentation.

Do the authors collect these IP addresses? 

Do they have a kind of a IP address circle of all users that ever used a particular app (the package id is collected, remember), do they do geo location lookup on those addresses?

It is an authoritative, closed source server and we have no idea what is being done there.

Sending the user's device IP address to a 3rd party server is also considered a **privacy breach**, and especially in Europe it will be [considered illegal](http://www.whitecase.com/publications/alert/ip-addresses-may-be-subject-eu-data-protection-laws). You, as app developer, will have to **explicitly** state that this is being done in the privacy policy of your app!

## Adsense Issues

There are important issues with adsense as well. 

First problem is that the authoritative server may, at any time, [inject their own banner in your app](https://github.com/userweb/expose-liar-plugin/blob/master/GenericAdPlugin.java#L375).
They configure the rate at which this happens, it might be 2%, but it might be 99%. You never know and may never be sure. Since it is a closed source server code, it could even
be unintentional, due to a bug or something. The result? 

At best, no ads will be shown, at worse you will be making money for someone else all the time.

Another part of the problem is the [Block ads by sensitive category](https://support.google.com/adsense/answer/164131?hl=en) Google Adsense configurations. 
In your Google AdSense account you [may decide](https://support.google.com/adsense/answer/3016459?hl=en&ref_topic=23390) what type of ads to block for your users, e.g., sexual content, etc.

With the current code, there is 2% (or more, see below) chance that your rules will be **overriden** completely. Whatever you configured in your Google AdSense account will just not work, because the authoritative server replaces your banner and interstitial ids with the ones sent with the JSON reply. Your users may get offended and uninstall your app.

## Is it 2% banners? How long are the they shown?

First, I'm not so sure that Java pseudonumbers are the correct thing [to use here](https://github.com/userweb/expose-liar-plugin/blob/master/GenericAdPlugin.java#L380).
SecureRandom() provides more entropy, it might be that 2% happens 3 times in a row currently.

Second, the way I see it, this [adlic](https://github.com/userweb/expose-liar-plugin/blob/master/GenericAdPlugin.java#L363) call is done only **once your app initialises**.

This means, you will be showing the 2% authors' ads throughout the **whole time** a user uses your app. These 2% will be recalculated only if the users explicitly closes your app and therefore re-initialises the call to the authoritative server. I might be wrong here, so someone please review and comment on this.


## Free App Issues

Last, this really is NOT a free app. It should already be obvious. The authors make money from your app, even if it is 2%. This really isn't a problem, the problem is that they state it is free and open source, but the info about the 2% and the authoritative server is obscure. 

Also, important parts of the app, as shown in this thread, are also [closed source](https://github.com/floatinghotpot/cordova-extension/tree/master/src/android) [binary](https://github.com/floatinghotpot/cordova-extension/tree/master/src/ios) files committed in Github and *carefully* masked with the name `cordova-extension`.
Looking at the [README](https://github.com/floatinghotpot/cordova-extension/blob/master/README.md) it is totally unclear what this plugin does and what the binaries contain. In my opinion - this is unacceptable and quite frankly dangerous!


So, I urge the authors to revisit these points. I think this plugin is better suited as trial software. Use it 30 days for free and then pay for a license. This would be something I'd consider as well, but right now everything is quite obscure and it does indeed, really look like a scam. I'm sorry.

**Comment by becvert** [comment]
@jmelvin the 2% royalty is NOT documented in the README on github nor in the README on the npm registry.
The link to the Licence Agreement page is buried in the right hand side menu in the wiki.
Yes that [README](https://github.com/floatinghotpot/cordova-admob-pro/blob/master/docs/README.md) is a little bit better (have to go to the API overview to hear of the ad sharing though).

@rene-molineux thanks for these precisions

I'll opt out of this plugin.

**Comment by floatinghotpot** [comment]
@rene-molineux You post is very logical and reasonable, good points! I appreciate logic, not rude shouting. So I decide to reply in a good mood.

First, this one: https://github.com/floatinghotpot/cordova-plugin-admob

It is my first ad plugin project, fully open source, it's welcome and forked a lot. Sharing and fork, improve and send PR, it's the great culture that GitHub creates. I am okay with it, and even love it. 

But some guys just copy it, change a name, then publish to npm and claim as their own. I don't like such behavior.  :-(

At the same time, lots of guys hope to get a high-quality plugin, and they are willing to pay, for the product, and also for the support. Some companies also contact me for outsourcing project to write some Ad plugins, like this ones:
https://github.com/floatinghotpot/cordova-plugin-flurry
https://github.com/floatinghotpot/cordova-smart-adserver

After I've finished 7-8 Ad plugin outsourcing projects, I found most ad network SDKs are quite similar, the core part of the ad plugins can be highly reused. Then I re-architect and abstract the core part, to be reused by all ad plugins, and also add license control. This time, to avoid copier, I decided to close part of the code. ;-)

This is this project: https://github.com/floatinghotpot/cordova-admob-pro

Later, some indie from some poor country/area contact me, they have no paypal account, and even no enough money to pay for the license. Then I create another model (I call it partnership), they can use this plugin for free, ship my code with their app, just share me very little ad traffic (2% Ad or 2% user), that's the model we are disputing today.

So I summarize all 3 business models in the wiki License Agreement.

In later iteration, I found some guys attempt to reverse engineering my binary, crack my code, and generate fake license key, then I setup a server in cloud to anti-crack, adlic, means "Ad License". Each time the plugin initialize, it will send the license key to server for validation against the database records. That's why I ask userweb's package Id and license key for double check, but unfortunately, I did not get the answer I want. 

The above are the full story of the Ad plugins, open source one, and this pro one, and also the 3 business models.

As to privacy, or collecting user's IP, of course not, it's not my interests, and not my strength to be a hacker or spy like the guys in movie "Jason Bourne". I am only an indie, not CIA or FBI. :-)

Yes, @rene-molineux, you are correct, this plugin is not a 100% FREE plugin. It's mainly for commercial purpose, but it can be used for free (before you earn enough to afford the license fee). It's also okay to share very little Ad traffic instead of directly paying me cash or PayPal. 

I am quite open on how you use it, just do not copy, no fake license, no rude shouting. One thing is sure, quite a lot of developers from the poor countries/areas are benefited from this plugin and this creative model, so I believe this ad sharing model has nothing wrong.

Okay, I accept your urging points, to make it more precisely, now, I update the README with following content (Please help me check it's clarified enough clear):

---

You can use this plugin for free for trial purpose. If it earns less than $1000 for you, you can continue to use for free. 

If use in commercial project, please [get a license](http://rjfun.github.io/), if you have monetized more than $1000 using this plugin, you are also required to: either get a commercial license ($20) without ad sharing, or no need pay but share 2% Ad traffic, read the [License Agreement](https://github.com/floatinghotpot/cordova-admob-pro/wiki/License-Agreement) for details. As a commercial customer, you will be supported with high priority, via private email or even Skype chat.

If you hope to get a fully open source plugin and need DIY, use this one instead:
https://github.com/floatinghotpot/cordova-plugin-admob

---

**Comment by becvert** [comment]
@floatinghotpot that's better but you're still a bit shy.
I think that the Licence Agreement section or at leat a mention of the ad sharing needs to be near the top of the README. That's just my opinion.
You're not the only one whose giving time and putting effort for the community,
but you're probably one of the few who do earn money off of your plugins.
I'm not saying it's a bad thing and that you're a bad guy, 
but  indies like me deserve to be better informed.

Also, sorry to bother you, but you did not clearly respond to @userweb (even though he's used some rude shooting) about the adlicRate. he said he's not using a license key. True of false it's worth double checking. 
You lost me on this. For this reason and others, as I said I'm opting out of your plugin and I'll see if any differences occur.

probably my last post here ;)

**Comment by floatinghotpot** [comment]
One more word on cordova-extension project, it's another story. 

It's some bigger than a plugin only. I attempted to write something really cool, but still not achieve it yet. 

As we know, Cordova / Cocos2d-X / Unity are the most popular cross-platform app/game technology for mobile development. But only cordova ecosystem provides so many plugins with a very excellent architecture and convenient management utility. It's quite hard for find similar plugins for Cocos2d-X and Unity. People have to re-write plugins, even almost the same logic.

I was thinking and experimenting, why not reuse the code, is it possible to get them reusable for Cocos2d-X and Unity?

2 years ago, I spent more than 1 months, full time (actually 14 working hours a day, you know, sometimes when you have a crazy idea, you just cannot stop coding), working on an experimental project, a general plugin framework for Cocos2d-x to call Cordova plugins, I call it "Magpie", here:
https://github.com/HandyWit/magpie

As it's README states:

> Extend the Cordova plugin base class with adapter interface. Plugin written based on this interface, may also be reused for Unity, Cocos2d-X, and other frameworks.

Purpose

> Make Cordova Plugins reusable.

> To use mobile device native functionalities and integrate 3rd-party SDKs, mobile developers are writting hundreds plugins for Cordova, Unity, Cocos2d-X, and other frameworks.

> Can they be reused? Yes, it's possible.

> Cordova plugin manager is bridging function call between javascript and native languages, actually, it can be ported to bridge with C, C++, C#, then it can be reused for Unity, Cocos2d-X and other frameworks.

![Magpie project](https://github.com/HandyWit/magpie/raw/master/docs/architecture.jpg)

And here is the successful demo to call Cordova Plugins in Cocos2d-X Game:
https://github.com/HandyWit/MagpieDemo

Though the experiment is quite successful, but it's not easy to be used by community, and also no enough influence to get sponsor or volunteer to join me. 

I did not continue to write the adapter for Unity, it's only used in Cordova plugins, as it is till today.

**Comment by zabojad** [comment]
@floatinghotpot I have three open issues right now. Do you confirm that if I get a licence, you'll provide support until they are solved (if due to bugs in the plugin, then you'll fix them) ?

**Comment by rene-molineux** [comment]
@floatinghotpot Fair enough and thanks for the clarifications! Like I said, it is OK to get paid for working on something, this is fair.

I'd advise putting the 2% and license info & link under a section called **License** or something in the README.md. That's where most users will look I think.

Other than that, I would also add the info about the data sent to your adlic server. Please understand, this really could be an issue in some countries or in some commercial environments. 

Also,  in the 2% explanation you should also include the info that any Admob rules a user has made will not affect the case where your 2% ads are shown. Just for clarity.

Other than that, good work!

**Comment by floatinghotpot** [comment]
@zabojad If you are a commercial customer, please drop me a private email (rjfun.mobile at gmail.com) and show us your license. We will try our best to provide support. 

At the same time, please be aware that we can only resolve the bugs in our plugin. If it's the problem or limitation in your own code or in AdMob SDK, it's out of our capability, then need turn to Google AdMob official forum or stackoverflow.com for help.

**Comment by bflopez** [comment]
I just want a quick summary. Right now I am making very little. Like $10 a month. Once I have made $1000 you will start taking 2% unless I buy a license. Is this correct?

**Comment by bflopez** [comment]
Is it $20 per app or a one time license for a Dev?

**Comment by bflopez** [comment]
@rene-molineux @userweb @becvert Do you guys have any other plugins you recommend? I might fork the open source just to update AdMob SDK. This is a big issue for me right now. Time is of the essence as always.

**Comment by bflopez** [comment]
@rene-molineux Also thanks for the in depth analysis. @floatinghotpot Thank you for taking pride in your work and working with us about this issue.

**Comment by floatinghotpot** [comment]
@rene-molineux Thanks for the reminder about privacy. I just update the License Agreement with following content:

---

## Privacy Statement

When this plugin is initialized, it will send license key and app id to our license control servers, only for validation it's used with legal authorization. It won't collect any user's IP or any privacy data and store in our server.

The plugin is built based on AdMob SDK, when your app send Ad request to AdMob servers, Google's server might collect user's IP for big data analysis and Ad optimization purpose. It's covered by Google's policy, not ours.

If you want to increase accuracy of Ad publishing to improve click rate, targeting the right users is a good idea. You may optionally send the gender/age/location info to Google Ad server by setting the related info in the API. It's your own behavior and responsibility to balance the pros/cons, nothing to do with us.

**Comment by bflopez** [comment]
@floatinghotpot Is it $20 per app or a one time license for a Developer?

**Comment by becvert** [comment]
@bflopez 

So far [cordova-plugin-admob-free](https://github.com/ratson/cordova-plugin-admob-free) is the only one I've seen that's completely free, without ad sharing and full open source.
It's basically a fork of cordova-plugin-admob-simple with the ad sharing removed.

cordova-plugin-admob-simple itself probably just copied @floatinghotpot's work.
I opened an issue over there about the 2% ad sharing, the guy edited my message and closed the issue in just under a few minutes. seems very dishonest. a scam.

All other plugins seem to do ad sharing.
And no one advertises it properly.
very deceitful.

Anyway I'm looking into improving cordova-plugin-admob-free and adding mediation for the Facebook Audience Network right now.

Still you may consider admobpro if you don't mind licence fee or ad sharing and need support plus more mediation networks.

**Comment by becvert** [comment]
@floatinghotpot 

you write 

> You can use this plugin for free during trial purpose. If it earns less than $1000 for you, you can continue to use for free.
> 
> If use in commercial project, please get a license, or, you have monetized more than $1000 using this plugin, you are also required to: either get a commercial license ($20), or, no need pay but share 2% Ad traffic

I do believe until you get a licence key a 2% ad sharing is applied. it's never completely free?
So non commercial project earning less than $1000 are penalized too?
Please correct me If I'm wrong.

Thank you.

**Comment by floatinghotpot** [comment]
@becvert 

> You can use this plugin for free during trial purpose. If it earns less than $1000 for you, you can continue to use for free.

Only abuse of this plugin, for example, attempt to crack, reverse-engineer, generate a fake license key, or steal a license key from others, such behavior will be penalized.

Frankly speaking, time is valuable and limited to anyone. It cost us time to work on this project, especially provide support by replying the questions and reply emails one by one. It's fair that I get rewarded. If you want my support completely free, then you are consuming my time for FREE. It's not fair.

This project is also created by me, it's completely FREE: https://github.com/floatinghotpot/cordova-plugin-admob

**Comment by becvert** [comment]
@floatinghotpot you're missing the point. I'm just trying to help you out.
Again reading the source code, I think the 2% penalty is applied until one get a licence.
But this is not what I understand reading the licence agreement.
I'm just saying the wording needs reviewing again. Maybe I'm wrong about it.

And please stop saying your time is valuable.
I have a few plugins of my own, I don't make a fuss about my precious time.
Plus I don't get paid for it either.
How many devs out there are giving time and effort to the cordova community?
How many are rewarded?

Sorry I'm just a bit pissed, not especially at you, but at all those admobs plugins that are being dishonest. I feel it is not in the good spirit of the open cordova community.

To complete my previous post, cordova-plugin-admob-free is the only one free along with yours cordova-plugin-admob obviously.

**Comment by floatinghotpot** [comment]
@becvert Let's stop arguing and make things simple. 

* cordova-plugin-admob, it's FREE and fully open source, it's donated to community and we appreciate the good spirit. Welcome to fork, improve, send PR. :-)

**Comment by becvert** [comment]
I'm not arguing about cordova-plugin-admob (thanks for the donation)
I'm arguing about cordova-plugin-admobpro.

Besides please allow me to say that iAd has been discontinued,
so you should probably remove the iAd PluginPro license payment option

**Comment by floatinghotpot** [comment]
Linux (free and open source), and Mac (commercial with support), both have their own reason to exist, and live together peacefully. ;-)

Thanks for the reminder about iAd. 👍   I will remove it from related docs.

**Comment by becvert** [comment]
@floatinghotpot that's not the point.
I'm fine with admobpro.
The wording though does not reflect what's happening in your code.
You should write 

> until you buy a licence, a 2% ad sharing is applied

That's all I'm saying :wink:

**Comment by InkOut** [comment]
I thought that i give you only 2%, but i checked url and saw, that 2% is 30%.

500$ each month. LOL! Thief!

**Comment by showthetrue** [comment]
https://github.com/floatinghotpot/cordova-admob-pro/issues/640

FROM A FRIEND:

Read the license and you can see, that he promised to take only 2 percent of ad traffic, but in fact he takes up to 30%.

Why am I writing this?

Because I noticed that my money was also stolen and good must defeat evil

How did you know my mail?

I spent a lot of money and time to parse all google play apps (yes, +2.2M apps), and I found all the applications that use this plugin

What should I do?

First, do not write to the creator of the plugin. I do not know what he can do in a panic, but he can control your ad traffic, so trust me and be ninja.

Second, make an update without this plugin.

**Comment by showthetrue** [comment]
@floatinghotpot   you is  a fuckingggg   LIER !!!!!!!!
