### ISSUE TITLE
iOS 10 Permissions

### ISSUE THREAD

**Issue by Chuckv01** [floatinghotpot/cordova-admob-pro#459]
iOS 10 requires descriptions of the permissions the admob sdk requests. App submission will be rejected until you add these permissions to your iOS plist file. Apple will send you this email when you submit your app for processing:

`This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSCalendarsUsageDescription key with a string value explaining to the user how the app uses this data.`

`This app attempts to access privacy-sensitive data without a usage description. The app's Info.plist must contain an NSBluetoothPeripheralUsageDescription key with a string value explaining to the user how the app uses this data.`

Steps to workaround the issue:

1. `cordova plugin add cordova-plugin-settings-hook --save`
2. Add these descriptions of the permission in your ios platform config.xml:

        <platform name="ios">
        <config-file parent="NSCalendarsUsageDescription" platform="ios" target="*-Info.plist">
            <string>Advertisement would like to create a calendar event.</string>
        </config-file>
        <config-file parent="NSPhotoLibraryUsageDescription" platform="ios" target="*-Info.plist">
            <string>Advertisement would like to store a photo.</string>
        </config-file>
        <config-file parent="NSBluetoothPeripheralUsageDescription" platform="ios" target="*-Info.plist">
            <string>Advertisement would like to use bluetooth.</string>
        </config-file>
        </platform>

**Comment by ngystvn90** [comment]
Can anybody confirm this fix?

**Comment by bflopez** [comment]
It works because it is what Apple requires now. Google updated their SDK so that this is not necessary. http://googleadsdeveloper.blogspot.com/2016/09/use-google-mobile-ads-sdk-7110-to.html Will this plugin be updating to the new SDK soon? I don't want my users clicking allow 3 times the first time they open my app and even worse because of an ad. Thank you.

**Comment by Chuckv01** [comment]
@bflopez The permissions are not requested on startup. They are only requested if a user clicks an ad that uses one of the special permissions.

That said, I agree it would be nice to have the admob sdk updated so this would not be necessary.

**Comment by bflopez** [comment]
@Chuckv01 Oh I see. Thank you. To me that is even worse. You are about to make a few cents and you get permission requests. I could easily see this preventing users from going through with the click. Or do we still get the click if the user turns around and Doesn't Allow the permission?

**Comment by floatinghotpot** [comment]
Hi guys, don't worry, I will immediately update the SDK. As always, this plugin will keep up to date.

**Comment by floatinghotpot** [comment]
I've updated the SDK to 7.11.0, and tested pass on my device. 

Now it's published to npm as cordova-plugin-admob@2.20.0.

**Comment by bflopez** [comment]
@floatinghotpot Thank you so much! I appreciate your hard work. I would like to buy a license for your plugin if it is developer specific and not app specific. If that is not the case could I also interest you in updating your open source cordova plugin? I opened an issue on that repository earlier today. Sorry for all the hassle.

**Comment by floatinghotpot** [comment]
@bflopez It's not a good practice to ask the same question in lots of threads. You know, reading and answering questions also cost me time (time is money). Please delete the same questions from other threads.

I am quite open on how you use the plugin. As it seems $20 means a lot to you, as you mentioned, you only earn $10 a month. You can use this plugin for FREE, until you earn enough to pay for the license fee.

Let's focus on the topic. Please verify the new plugin, if it's resolved, then let's close this issue.

**Comment by bflopez** [comment]
@floatinghotpot It isn't good practice to ignore questions but answer others on the very same thread either. Why do you give people so much trouble when they want to know more about your service always stating that "time is money"? I am literally begging you to take my $20 because I don't want to use a free version or share 2% of my ad revenue and you belittle me saying that it must be a lot of money for me and to not worry. I had to ask multiple times because you have been ignoring me all day. Remember time is money. That is your motto but it seems to only apply to you? Look I don't want to get into an argument. I know you have been dealing with a lot of frustration with your AdMob plugins this past couple weeks and I do not want to cause more. I deleted my questions from the other threads as you wished. I will email you about buying a license tomorrow since it seems you are open to it being developer specific and not just app specific. I am going to bed now but if someone hasn't verified that your update works I will do it first thing in the morning to help you close the issue. Again, thank you, I apologize for the repeated questions and all I ask is that you treat me with respect as I have been treating you.

**Comment by floatinghotpot** [comment]
@bflopez I apologize if you feel some impatience from my reply. Thanks for your kind cooperation on deleting the extra questions. Let focus and keep thing simple. The license fee of $20 is more symbolic than actual income. As to developer specific, or app specific, I don't care that too much. But I hope the time used on support won't be too much. Enjoy a good night. :-)

**Comment by bflopez** [comment]
@floatinghotpot I apologize for being slightly hostile. Thank you for your time. I know it is valuable. And no I won't need much support haha. Your plugin is very easy to use and have never had an issue with it. This SDK issue was the only thing that has come up since I have started using your plugin and it was something neither of us had control over. :) Good night buddy.

**Comment by Chuckv01** [comment]
@floatinghotpot Thanks for the fix! You're the best!

**Comment by bflopez** [comment]
@floatinghotpot I can also confirm it works. Thank you!

**Comment by floatinghotpot** [comment]
Thanks for the verification. Then issue closed. Cheers!

**Comment by rodolfocop** [comment]
Here's a link to a complete workaround from Google: https://groups.google.com/d/msg/google-admob-ads-sdk/UmeVUDrcDaw/HIXR0kjUAgAJ
